workflows:
  web-workflow:
    name: Web Build & Deploy
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Analyze
        script: flutter analyze
      - name: Tests
        script: flutter test
      - name: Build Web
        script: flutter build web --release
    artifacts:
      - build/web/**
    publishing:
      scripts:
        - name: Deploy to Netlify
          script: |
            # pip install netlify-cli
            # netlify deploy --dir=build/web --prod
            echo "Netlify deploy script placeholder"
